site_name: Aldair's Info

theme:
  name: material
  custom_dir: overrides
  palette:
          primary: blue grey
          accent: blue
  icon:
          logo: material/wizard-hat
  favicon: assets/wizard-hat.png

extra_css:
        - stylesheets/extra.css

extra_javascript:
        - javascripts/stats_calculator.js
        - javascripts/hp_calculator.js
        - javascripts/mp_calculator.js
        - javascripts/exp_calculator.js
        - javascripts/tablesort.min.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Resources: resources.md
  - Classes:
          - Overview: classes/overview.md
          - Guides: classes/guides.md
          - Stats: classes/stats.md
          - Specializations: classes/specializations.md
          - Subbing: classes/subbing.md
          - Ascending: classes/ascending.md
          - Mastering: classes/mastering.md
          - Grand Mastering: classes/grand_mastering.md
          - Transcending: classes/transcending.md
  - Quests: quests/overview.md
  - Hunting: hunting.md
  - Knowledge: knowledge/overview.md
  - Fragments: fragments.md
  - Crafting: crafting/overview.md
  - Spells:
          - Priest: spells/priest.md
  - Weapons:
          - All: weapons/all.md
          - Monk: weapons/monk.md
          - Priest: weapons/priest.md
          - Rogue: weapons/rogue.md
          - Warrior: weapons/warrior.md
          - Wizard: weapons/wizard.md
  - Armour:
          - All: armour/all.md
  - Maps and Coords: maps/overview.md
  - Tools:
          - Stats Calculator: tools/stats_calculator.md
          - HP Calculator: tools/hp_calculator.md
          - MP Calculator: tools/mp_calculator.md
          - EXP Calculator: tools/exp_calculator.md

